### PR TITLE
Transform siblings

### LINKED ISSUE #205: SlowCheetah preview transform does not work when the items are siblings
If `App.config` and `App.Debug.config` are siblings (missing the `DependentUpon` metadata), previewing transform will open their parent. SlowCheetah should account for this and support this structure.

### PR DESCRIPTION
**Pull request by davilimap**
Support transformation for items that are siblings in the project. Searches for sibling with compatible name on Preview Transform. Fixes the special case for web.config transformation to allow files with similar names to be recognized as normal configuration files or if the project is not web, allow web.config transforms.

Adds test class for SlowCheetah.VisualStudio with tests for newly created methods.

Closes #205, #154 and #56.

### CODE REVIEW

File: SlowCheetah.VisualStudio/Utilities/PackageUtilities.cs [hunk 1]
```diff
@@ -93,5 +96,48 @@ public static bool IsXmlFile(string filepath)
...
+                return false;
+            }
+            else
+            {
+                string docNameNoExt = Path.GetFileNameWithoutExtension(documentName);
+                string trnNameNoExt = Path.GetFileNameWithoutExtension(transformName);
+                Regex regex = new Regex("^" + docNameNoExt + @"\.", RegexOptions.IgnoreCase);
+                string configName = regex.Replace(trnNameNoExt, "");
+                return (!configName.Equals(trnNameNoExt) && configs.Any(s => { return string.Compare(s, configName, true) == 0; }));
+
```
Comment (jviau) [inline SlowCheetah.VisualStudio/Utilities/PackageUtilities.cs]: remove extra new line

File: SlowCheetah.VisualStudio/Utilities/PackageUtilities.cs [hunk 2]
```diff
@@ -93,5 +96,48 @@ public static bool IsXmlFile(string filepath)
...
+            }
+        }
+
+        /// <summary>
+        /// Gets an item from the project hierarchy
+        /// </summary>
+        /// <typeparam name="T">Type of object to be fetched</typeparam>
+        /// <param name="pHierarchy">Current IVsHierarchy</param>
+        /// <param name="itemID">ID of the desired item in the project</param>
+        /// <returns>The deired object typed to T</returns>
```
Comment (jviau) [inline SlowCheetah.VisualStudio/Utilities/PackageUtilities.cs]: Spelling `deired` -> `desired`

File: SlowCheetah.VisualStudio/Utilities/ProjectUtilities.cs [hunk 3]
```diff
@@ -97,5 +107,25 @@ private static IEnumerable<string> GetSupportedExtensions(IVsSettingsManager set
...
+                string projectTypeGuids;
+                aggregatableProject.GetAggregateProjectTypeGuids(out projectTypeGuids);
+                List<string> guids = new List<string>(projectTypeGuids.Split(';'));
+                return guids.Contains(Resources.Resources.WebAppGuid);
+            }
+
+            return false;
+        }
     }
 }
```
Comment (jviau) [inline SlowCheetah.VisualStudio/Utilities/ProjectUtilities.cs]: new line at end of file

File: SlowCheetah.VisualStudio.Tests/PackageUtilitiesTest.cs [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+    /// Test class for <see cref="PackageUtilities"/>
+    /// </summary>
+    public class PackageUtilitiesTest
+    {
+        IEnumerable<string> baseTestProjectConfigs = new List<string>(new string[] { "Debug", "Release"});
+
+        /// <summary>
+        /// Tests <see cref="PackageUtilities.IsFileTransform(string, string, IEnumerable{string})"/> returns on arguments that are null or empty strings
+        /// </summary>
+        [Fact]
```
Comment (jviau) [inline SlowCheetah.VisualStudio.Tests/PackageUtilitiesTest.cs]: Consider using `[Theory]`. Several of the tests here can be changed to use it.
